// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class DetalleFactura
{
    public int NroDetalle { get; set; }

    public int? NroFactura { get; set; }

    public int? MedicamentoId { get; set; }

    public int? Cantidad { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public decimal? Descuento { get; set; }

    public virtual Medicamento Medicamento { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}