// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public int? IdCliente { get; set; }

    public int? IdSucursal { get; set; }

    public DateOnly? FechaVenta { get; set; }

    public decimal? Total { get; set; }

    public string FormaPago { get; set; }

    public int? IdEmpleado { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual Sucursal IdSucursalNavigation { get; set; }
}