// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class Login
{
    public int IdLogin { get; set; }

    public string Usuario { get; set; }

    public string Contraseña { get; set; }
}