// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class Medicamento
{
    public int MedicamentoId { get; set; }

    public int? CodigoBarras { get; set; }

    public string Nombre { get; set; }

    public bool? RequiereAutorizacion { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public decimal? Precio { get; set; }

    public int? Cantidad { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();
}