// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class ObraSocial
{
    public int ObraSocialId { get; set; }

    public string Nombre { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}