// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaciaLibrary.Models;

public partial class Sucursal
{
    public int IdSucursal { get; set; }

    public string Direccion { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}